// <auto-generated />
using GrmDigitalTask.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrmDigitalTask.Migrations
{
    [DbContext(typeof(GrmTaskDbContext))]
    [Migration("20220629085738_Inicijalna")]
    partial class Inicijalna
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrmDigitalTask.EntityModels.GrmTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("GrmTask");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Item1",
                            Position = 0,
                            Score = 0
                        },
                        new
                        {
                            ID = 2,
                            Name = "Item2",
                            Position = 0,
                            Score = 0
                        },
                        new
                        {
                            ID = 3,
                            Name = "Item3",
                            Position = 0,
                            Score = 0
                        },
                        new
                        {
                            ID = 4,
                            Name = "Item4",
                            Position = 0,
                            Score = 0
                        },
                        new
                        {
                            ID = 5,
                            Name = "Item5",
                            Position = 0,
                            Score = 0
                        },
                        new
                        {
                            ID = 6,
                            Name = "Item6",
                            Position = 0,
                            Score = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
